name: kids_drawing_app
description: A fun and engaging drawing app for kids to explore their creativity.

publish_to: 'none' # Since this is a personal project

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_drawing_board: ^0.9.2  # For drawing functionality
  flutter_colorpicker: ^1.0.3    # For color selection

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/drawing_kid.png  # Add your splash screen image here
