name: kids_drawing_app
description: A fun and engaging drawing app for kids to explore their creativity.

publish_to: 'none' # Since this is a personal project

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_drawing_board: ^0.9.2  # For drawing functionality
  flutter_colorpicker: ^1.0.3    # For color selection

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/94262c50-9a84-438e-bf1f-2207494a750b.jpg  # Splash Screen Image
    - assets/fd6bac13-d4d6-423d-bac3-7e981384c20b.jpg  # Drawing Board Image
